### ISSUE TITLE
[Feature] Nonportable bucket maintenance

### ISSUE THREAD

**Issue by itsmeboy0** [ScoopInstaller/Nonportable#1]
#### Is your feature request related to a problem? Please describe.
@TheRandomLabs has been absent for over a year, and most of his buckets are just maintained by CI. New PRs are not being reviewed for a long time, and as `nonportable` is an official bucket, I think this calls for a maintenance change.

#### Describe the solution you'd like
Move/Fork the [`nonportable`](https://github.com/TheRandomLabs/scoop-nonportable) bucket to this organization.

#### Describe alternatives you've considered
Or maybe someone active can take over the bucket.

**Comment by issaclin32** [comment]
I sent a ticket to Github to **detach** this repo from `TheRandomLabs/scoop-nonportable`.

**Comment by itsmeboy0** [comment]
As of https://github.com/ScoopInstaller/Scoop/releases/tag/v0.2.1, the buckets URL has been updated to point to this repo, and as such, this is now resolved.
