### ISSUE TITLE
[Request] Vjredist

### ISSUE THREAD

**Issue by ppvnf** [ScoopInstaller/Nonportable#116]
**Name:** Microsoft Visual J# Version 2.0 Redistributable Package

**Description:** The Microsoft Visual J#™ Redistributable Package version 2.0 includes everything you need to run your Visual J# applications on a computer that already has the Microsoft .NET Framework v2.0 installed.

**Homepage:** https://www.microsoft.com/en-us/download/details.aspx?id=4712

**Download link(s):** https://download.microsoft.com/download/9/a/0/9a01eb1e-fe80-41af-a3f8-ea41220918f7/vjredist.exe

**Some indication of popularity/repute:** Microsoft's Java clone

**License:** https://social.msdn.microsoft.com/Forums/en-US/28a369b0-c1dc-4276-ac65-f063578fb139/redistributable-license?forum=visualjsharpgeneral
<br>
**PS: I tried... https://github.com/ScoopInstaller/Nonportable/pull/95/files**

**Comment by Zliced13** [comment]
I don't think this can be added to Scoop, the silent switch does not get rid of the interactive part of the installer.

**Comment by Zliced13** [comment]
Sorry @ppvnf for the incovience.
