### ISSUE TITLE
[Request] GameLoop (Android Emulator)

### ISSUE THREAD

**Issue by cloudmaker97** [ScoopInstaller/Nonportable#14]
### Criteria

For a package to be acceptable in the Nonportable bucket, it should be:
- [x] a reasonably well-known and widely used application
- [x] the latest stable version of the program
- [x] the full version i.e. not a trial version
- [x] a fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Information

**Name:** GameLoop
**Description:** With GameLoop, users can download and use hundreds of mobile **games and applications** on PC for free. It's like bluestacks but without 
**Homepage:** [GameLoop.com](https://www.gameloop.com/)
**Download link(s):** [Download](https://down.gameloop.com/k_pack_up/16229/c22158645/GLP_installer_1000218273_com.tencent.ig.exe)

**Comment by issaclin32** [comment]
I couldn't find any official **changelog** for this app.

The only information that I can find is the `version info` in the installer exe itself, which says `1.0.0.1`, and I am not sure if this can reflect minor changes of the app.

I will observe the changes for a few weeks, and decide whether this app is viable for *Scoop*.

**Comment by Dabombber** [comment]
This might be better placed in the unofficial [emulators](https://github.com/hermanjustnu/scoop-emulators) bucket.

**Comment by issaclin32** [comment]
> This might be better placed in the unofficial [emulators](https://github.com/hermanjustnu/scoop-emulators) bucket.

Thanks for the suggestion. I am fine with this app in the *Nonportable* bucket, see [Nonportable/bluestacks](https://github.com/ScoopInstaller/Nonportable/blob/master/bucket/bluestacks-np.json) for example.

But first, we have to find a proper way to **(1)** keep track of minor updates, and **(2)** silently install and remove it.

**Comment by issaclin32** [comment]
It is possible to track the version by [this page](https://www.gameloop.com/product/gameloop-download).
Sadly I could not find a **silent switch** for the installer, or a proper way to extract it.

The page has
```
"defaultMarketUrl":"https:\u002F\u002Fdown.gameloop.com\u002Fchannel\u002F3\u002F16412\u002FGLP_installer_1000218456_market.exe","defaultMarket64Url":""}
```
where **16412** can be used as the *version*.
