### ISSUE TITLE
 spotx-np: can't install

### ISSUE THREAD

**Issue by soredake** [ScoopInstaller/Nonportable#193]
## Bug Report

**Package Name:**  spotx-np

### Current Behaviour

```
❯ scoop install spotx-np
Installing 'spotx-np' (1.7-20230516-ad7d5b) [64bit] from nonportable bucket
Loading Install.ps1 from cache
Checking hash of Install.ps1 ... ok.
Running installer script...
Install.ps1:
Line |
   4 |  … spoti -confirm_spoti_recomended_over -podcasts_off -cache_off -block_ …
     |                                                       ~~~~~~~~~~
     | A parameter cannot be found that matches parameter name 'cache_off'.
Linking ~\scoop\apps\spotx-np\current => ~\scoop\apps\spotx-np\1.7-20230516-ad7d5b
'spotx-np' (1.7-20230516-ad7d5b) was installed successfully!
```
### Expected Behaviour

spotx-np installed.

### Additional context/output

Cache parameter was changed https://github.com/amd64fox/SpotX/commit/ad7d5b0f728273c084b0fe9bb0a8d3cf39e3c4c2

### System details

**Windows version:** 11

**OS architecture:** 64bit

**PowerShell version:** 7.3.2

**Additional software:** [(optional) e.g. ConEmu, Git]

#### Scoop Configuration

```json
//# Your configuration here
```

**Comment by soredake** [comment]
@amd64fox @kazzarin @rasa

**Comment by amd64fox** [comment]
#191

**Comment by drewbitt** [comment]
@amd64fox why was the PR closed? I understand it's frustrating that there's no maintainer merging for a few months now

**Comment by amd64fox** [comment]
If it's important for you to use SpotX via Scoop, then create and use your own bucket. Why wait for them for half a year or more?

**Comment by Ast3risk-ops** [comment]
https://github.com/Ast3risk-ops/spotx-bucket I've done that for you, using the changes from your PR

**Comment by drewbitt** [comment]
Cool @Ast3risk-ops ! Although name collisions dont matter in scoop since you can install "bucketname/package"

**Comment by Ast3risk-ops** [comment]
> Cool @Ast3risk-ops ! Although name collisions dont matter in scoop since you can install "bucketname/package"

Indeed. But I like being able to call packages without the bucket identifier, so the name change allows that.

**Comment by soredake** [comment]
This repo is unmaintained, closing.
