### ISSUE TITLE
qttabbar-np failed installation 

### ISSUE THREAD

**Issue by KrisSchneider** [ScoopInstaller/Nonportable#20]
## Bug Report

**Package Name:** [name of package which has bug(s)]
qttabbar-np

### Current Behaviour
qttabbar-np is not installing properly.

### Expected Behaviour
qttabbar-np should install properly.

### Additional context/output
![(WindowsTerminal)z6C8p1_07-05-2022](https://user-images.githubusercontent.com/101912712/177460369-4924edc0-a458-48f9-8f60-3c1669eb50f7.jpg)

![(WindowsTerminal)h047L1_07-05-2022](https://user-images.githubusercontent.com/101912712/177460581-d3f48ce1-d754-4fc3-97df-914954b8b8ae.jpg)

```powershell
PS C:\Users\krist> scoop install qttabbar-np
Installing 'qttabbar-np' (1043) [64bit]
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 0ed81a|OK  |   2.3MiB/s|C:/Users/krist/scoop/cache/qttabbar-np#1043#http_qttabbar.wdfiles.com_local--files_qttabbar_QTTabBar_1043.zip
Download: Status Legend:
Download: (OK):download completed.
Checking hash of QTTabBar_1043.zip ... ok.
Extracting QTTabBar_1043.zip ... done.
Running installer script...
Get-WmiObject:
Line |
  15 |  Get-WmiObject Win32_Process -Filter "name = 'msiexec.exe'" | Where-Ob …
     |  ~~~~~~~~~~~~~
     | The term 'Get-WmiObject' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
ERROR Exit code was 1603!
Remove-Item:
Line |
  18 |  Remove-Item "$dir\QTTabBar.exe"
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Access to the path 'C:\Users\krist\scoop\apps\qttabbar-np\1043\QTTabBar.exe' is denied.
Linking ~\scoop\apps\qttabbar-np\current => ~\scoop\apps\qttabbar-np\1043
'qttabbar-np' (1043) was installed successfully!
```

```powershell
PS C:\Users\krist> scoop uninstall qttabbar-np -p
Uninstalling 'qttabbar-np' (1043).
Running uninstaller script...
ERROR Exit code was 1605!
Unlinking ~\scoop\apps\qttabbar-np\current
Removing persisted data.
'qttabbar-np' was uninstalled.

```

### System details

**Windows version:** [e.g. 7, 8, 10]
10

**OS architecture:** [e.g. 32bit, 64bit]
64bit

**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`]
7.2.5

**Additional software:** [(optional) e.g. ConEmu, Git]
gsudo

#### Scoop Configuration

```json
{
  "lastUpdate": "2022-07-05T21:00:30.7425744-06:00",
  "SCOOP_REPO": "https://github.com/ScoopInstaller/Scoop",
  "SCOOP_BRANCH": "master",
  "aria2-warning-enabled": false
}
```

**Comment by issaclin32** [comment]
Thanks for reporting.
The problem is caused by that:
**(1)** `Get-WmiObject` is not supported in Powershell 7. (using `Get-CimInstance` instead)
**(2)** Version 1043 does not install properly on Windows 10 21H1 or above. Therefore we need to update the app to 2048-beta2.

**Comment by KrisSchneider** [comment]
Oh ok, let me try it PowerShell 5, and I'll show my results afterwards.

**Comment by KrisSchneider** [comment]
It worked, I installed with no problems.

**Comment by issaclin32** [comment]
> Oh ok, let me try it PowerShell 5, and I'll show my results afterwards.

I fixed the problem in https://github.com/ScoopInstaller/Nonportable/commit/5310c37e85f2120a9d5f740e9c3aad4fb1c9ad09
This package should work no matter you are using Powershell 5 or 7.
