### ISSUE TITLE
calibre-np unable to update from 6.x to 7.x version

### ISSUE THREAD

**Issue by howardCodeGit** [ScoopInstaller/Nonportable#249]
## Bug Report

**Package Name:** [name of package which has bug(s)]
calibre-np

### Current Behaviour
Unable to update from current version of 6.29.0 to 7.0.0 or 7.1.0

### Expected Behaviour
Expected to upgrade from calibre 6.29 to 7.xf

### Additional context/output

```
Download: (OK):download completed.
Checking hash of calibre-64bit-7.1.0.msi ... ok.
Uninstalling 'calibre-np' (6.29.0)
Installing 'calibre-np' (7.1.0) [64bit] from nonportable bucket
Loading calibre-64bit-7.1.0.msi from cache.
Extracting calibre-64bit-7.1.0.msi ... Exception: C:\Users\username\scoop\apps\scoop\current\lib\core.ps1:638
Line |
 638 |          throw "Could not find '$(fname $from)'! (error $($proc.ExitCo …
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Could not find 'Calibre2'! (error 16)
```

### System details

**Windows version:** [e.g. 7, 8, 10]
Windows 11

**OS architecture:** [e.g. 32bit, 64bit] 
64-bit

**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`]
7.4.0

**Additional software:** [(optional) e.g. ConEmu, Git]

#### Scoop Configuration

```json
{
  "alias": {
    "i": "scoop-i",
    "add": "scoop-add",
    "rm": "scoop-rm",
    "remove": "scoop-remove",
    "ls": "scoop-ls",
    "u": "scoop-u",
    "upgrade": "scoop-upgrade"
  },
  "last_update": "2023-11-26T16:31:59.0806645-05:00",
  "scoop_branch": "master",
  "scoop_repo": "https://github.com/lukesampson/scoop"
}

```

**Comment by SorYoshino** [comment]
Thank you for reporting the issue! It has now been resolved in https://github.com/ScoopInstaller/Nonportable/commit/d51091a89eb65e5134cc2e69287a5d5850c1fbcb
