### ISSUE TITLE
nvidia-display-driver-dch-np: checkver still error

### ISSUE THREAD

**Issue by Lutra-Fs** [ScoopInstaller/Nonportable#45]
## Bug Report

**Package Name:** nvidia-display-driver-dch-np
### Current Behaviour

version 471.41

### Expected Behaviour

should be larger than 500

### Possible Solution

The ```checkver``` is still wrong after May update. The DCH driver is designed for windows 10/11 so should not stay with win7's osid in url

### System details

**Windows version:** [e.g. 7, 8, 10]

**OS architecture:** [e.g. 32bit, 64bit]

**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`]

**Additional software:** [(optional) e.g. ConEmu, Git]

#### Scoop Configuration

```json
//# Your configuration here
```

**Comment by Lutra-Fs** [comment]
I will start a PR if available. (Maybe next week)

**Comment by ppvnf** [comment]
any update on this?

nvidia-display-driver-np is also outdated

**Comment by Lutra-Fs** [comment]
tmr

**Comment by ppvnf** [comment]
Download links in case it helps:

https://www.nvidia.com/Download/processFind.aspx?lid=1&osid=57&dtcid=1
https://www.nvidia.com/download/driverResults.aspx/193714

**Comment by Lutra-Fs** [comment]
Hi @issaclin32,
I wonder why you revert your change for this package in f667fa78ca733cd39cce4c6844d22ab18a0f9d9b ? 
I think may be we should change `nvidia-display-driver-dch-np` to `nvidia-display-driver-np` and `nvidia-display-driver-np` to `nvidia-display-driver-standard-np` or some other name as it seems NVIDIA not distrbute standard package for Windows 10 and Windows 11 any more.

> https://www.nvidia.com/Download/index.aspx L2067-2070
>```javascript
>// HNote all Win-10/64 is dtcid=1, this over-rides all the regexp RTX stuff. RegExp('RTX .*Notebooks')).test
>//RVC Windows Server 2022 refactor to use name var dtcid = (((selProductSeriesType.value in { '1': '', '11': '', '3': '', '7': '' }) && (getSelectedOSIdValue() in { '57': '' })) || (getSelectedOSIdValue() in { '57': ''} && ddlDownloadTypeDch.value == "1")) ? "&dtcid=1" : "&dtcid=0"; // Only Win-10-64
>//RVC Windows 11 Jul-18-2021
>var dtcid = (((selProductSeriesType.value in { '1': '', '11': '', '3': '', '7': '' }) && (getSelectedOSName() in { 'Windows 10 64-bit': '', 'Windows Server 2022': '', 'Windows Server 2019': '', 'Windows Server 2016': '', 'Windows 11': '' })) || (getSelectedOSName() in { 'Windows 10 64-bit': '', 'Windows Server 2022': '', 'Windows Server 2019': '', 'Windows Server 2016': '', 'Windows 11': ''} && ddlDownloadTypeDch.value == "1")) ? "&dtcid=1" : "&dtcid=0"; // Only Win-10-64
>```
> L2181-2184
>```
>	//RVC Windows Server 2022 refactor to use name if ((dchFound == false) && (selProductSeriesType.value in { '1': '', '11': '', '3': '', '7': '' }) && (getSelectedOSIdValue() in { '57': '' })) // DCH Not available so see if STD is available for Win-10 GeForce and Titan and Quadro Sep-2020
>	//RVC Windows 11 Jul-18-2021
> if ((dchFound == false) && (selProductSeriesType.value in { '1': '', '11': '', '3': '', '7': '' }) && (getSelectedOSName() in { 'Windows 10 64-bit': '', 'Windows Server 2022': '', 'Windows Server 2019': '', 'Windows Server 2016': '', 'Windows 11': '' })) // DCH Not available so see if STD is available for Win-10 GeForce and Titan and Quadro Sep-2020
>```

**Comment by scowalt** [comment]
I think I have this working in my scoop bucket: https://github.com/scowalt/scoop-apps/blob/main/bucket/geforce-game-ready-driver.json

I'll open a PR for this, but if I forget or it gets rejected, someone else can start there. You can also look at the scoop package for inspiration https://github.com/AeliusSaionji/chocopkgs/tree/master/geforce-game-ready-driver
