### ISSUE TITLE
Incoming parameters for a package

### ISSUE THREAD

**Issue by amd64fox** [ScoopInstaller/Nonportable#47]
Hello, is there a way to add incoming parameters for a package?
Here is the manifest from [spotx](https://github.com/ScoopInstaller/Nonportable/blob/master/bucket/spotx-np.json), it uses incoming parameters, for example `-podcasts_off`, but it is not always needed by all users.

**Comment by issaclin32** [comment]
Sadly *Scoop* does not support imcoming parameters.

There are 2 ways to implement it:

**(1)** Add a new package, such as `spotx-with-podcasts-np`.

**(2)** Add a standalone **script** in `(BUCKET DIRECTORY)\scripts` that allows user to turn off podcasts, and put `notes` to notify users, such as:
```
"notes": "Run \"$dir\\turn-off-podcasts\" to turn off podcasts.",
```
See [extras/grepwin](https://github.com/ScoopInstaller/Extras/blob/master/bucket/grepwin.json) for example.

**Comment by amd64fox** [comment]
Thanks, I'll just leave it as it is.
