### ISSUE TITLE
Can't install ditto-np

### ISSUE THREAD

**Issue by energister** [ScoopInstaller/Nonportable#49]
## Bug Report

**Package Name:** ditto-np

### Current Behaviour

Popup appears with the message like "folder name must not contains symbols: / : * ? " < > |"
And installation fails.

### Additional context/output

Console log:
> C:\Users\60131474>sudo
> C:\Users\60131474# scoop install ditto-np
> Installing 'ditto-np' (3.24.214.0) [64bit] from nonportable bucket
> Loading DittoSetup_64bit_3_24_214_0.exe from cache
> Checking hash of DittoSetup_64bit_3_24_214_0.exe ... ok.
> Running installer... error.
> ERROR Exit code was 1!
> Installation aborted. You might need to run 'scoop uninstall ditto-np' before trying again.

Similar output while running from PowerShell.

### System details

**Windows version:** 10

**OS architecture:** 64bit

#### Scoop Configuration

```json
{
    "lastUpdate":  "2022-08-18T01:13:16.6648744+03:00",
    "SCOOP_REPO":  "https://github.com/ScoopInstaller/Scoop",
    "SCOOP_BRANCH":  "master"
}
```

**Comment by issaclin32** [comment]
Thank you for reporting.
The problem is related to a recent update in Scoop core. (https://github.com/ScoopInstaller/Scoop/pull/5065)
