### ISSUE TITLE
[Request] nvidia geforce experience

### ISSUE THREAD

**Issue by ppvnf** [ScoopInstaller/Nonportable#78]
https://github.com/ScoopInstaller/Extras/issues/7131

PackageIdentifier: nvidiageforceexperience
PackageVersion: 3.26.0.131
PackageLocale: en-US
Publisher: Nvidia
PackageName: nvidiageforceexperience
License: proprietary
ShortDescription: nvidia driver
Installers:

Architecture: x64
InstallerType: exe
InstallerUrl: https://us.download.nvidia.com/GFE/GFEClient/3.26.0.131/GeForce_Experience_v3.26.0.131.exe
ManifestType: singleton
ManifestVersion: 1.0.0

**Comment by Zliced13** [comment]
This package cannot be added because the uninstaller has no silent switches, making it unsuitable for official buckets. But, you can add this to your own bucket like many people have done already.

Ex. https://github.com/issaclin32/scoop-bucket/blob/master/bucket/nvidia-geforce-experience-np.json
