### ISSUE TITLE
[Request] EverythingToolbar

### ISSUE THREAD

**Issue by ppvnf** [ScoopInstaller/Nonportable#88]
https://github.com/ScoopInstaller/Extras/issues/8958

**Comment by Zliced13** [comment]
@ppvnf can you test if this works properly? It's in my personal bucket:
```
scoop bucket add MyScoop 'https://github.com/Zliced13/MyScoop'
```
```
scoop install everything-toolbar
```

**Comment by Zliced13** [comment]
It worked for me, how about you?

**Comment by ppvnf** [comment]
For some reason it requires admin privilege and even as admin unfortunately I am getting an error:

![Captura de tela 2022-11-13 065321](https://user-images.githubusercontent.com/73800734/201516364-ca158582-338e-418b-9ee0-d9a0d4e47bc1.png)

Even though it shows successful install I can't actually use everything-toolbar.

By the way, I believe the following instructions from https://github.com/stnkl/EverythingToolbar should be added to notes:

> "Enable EverythingToolbar via the context menu of the taskbar
> 
> Note: You will have to open the context menu twice as it doesn't show up the first time you open it.
> 
> Adjust size and position after unlocking the taskbar"

**Comment by Zliced13** [comment]
That's weird, it should have also installed `everything-toolbar-scripts` as-well, it's in the bucket.

**Comment by Zliced13** [comment]
Also, the manifest is now fixed it should now work with all versions of PowerShell (5-7).
![(WindowsTerminal)N4E2l3_11-13-2022](https://user-images.githubusercontent.com/101912712/201532500-5144ab15-ecee-4ec7-b39c-2087502d0a11.jpg)
![(WindowsTerminal)w8w3a3_11-13-2022](https://user-images.githubusercontent.com/101912712/201532504-7f4c6e1c-ed8b-4468-93cf-558f432a522e.jpg)

**Comment by ppvnf** [comment]
> Also, the manifest is now fixed it should now work with all versions of PowerShell (5-7). 

Thanks, it's working now (only as admin tho)
Also, how about adding some notes like I suggested in https://github.com/ScoopInstaller/Nonportable/issues/88#issuecomment-1312692555?

**Comment by Zliced13** [comment]
> > Also, the manifest is now fixed it should now work with all versions of PowerShell (5-7).
> 
> Thanks, it's working now (only as admin tho) Also, how about adding some notes like I suggested in [#88 (comment)](https://github.com/ScoopInstaller/Nonportable/issues/88#issuecomment-1312692555)?

That is because the **.cmd** scripts do not work without administrator privileges, which is why I added an **if** statement to check if the user is an admin or not an admin.

Also, I will add notes to the manifest. Thanks for the suggestion.

**Comment by ppvnf** [comment]
I am closing this issue since there's another one in https://github.com/ScoopInstaller/Extras/issues/8958
